version: "3.8"

services:
  frontend:
    build:
      context: ./
    ports:
      - "3000:3000"
    restart:
      always

  backend:
    build: 
      context: ./phoneme_research/fastapi
    ports:
      - "80:80"
    environment:
      - PYTHONUNBUFFERED=1
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"